### PR TITLE
For upstream/improvements

### PR DESCRIPTION
**Pull request by c0d3z3r0**

### CODE REVIEW

**Comment by jkadijk** [comment]
Thanks for all the improvements and the pull request!  I will pull these in to the repo when I've tested it.

**Comment by c0d3z3r0** [comment]
Great! :-)
Please let me know if there are any problems so I can fix them

**Comment by c0d3z3r0** [comment]
I encountered some problems... I'll push the fixes this week or so

**Comment by c0d3z3r0** [comment]
Some more fixes :)

**Pull request closed without merging**
